# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: octokit/request-action@v2.x
        id: get_pull_request_details
        with:
          route: GET /repos/{ownerRepo}/pulls/{pull_number}
          ownerRepo: ${{ github.repository }}
          pull_number: "1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: |
          echo latest release: ${{ steps.get_pull_request_details.outputs.data }}
          echo ${{ steps.get_pull_request_details.outputs.data }} | jq '.'
