# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: octokit/request-action@v2.x
        id: pr
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: peterjgrainger
          repo: actions-fun
          pull_number: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      - run: |
          id="${{ fromJSON(steps.pr.outputs.data.id) }}"
          login="${{ fromJSON(steps.pr.outputs.data.user.login) }}"
